# Generated by Django 4.2.1 on 2023-05-08 13:56

import apps.abstract.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=True, help_text="Objects not enabled can't be show.", verbose_name='Enabled?')),
                ('created_at', models.DateTimeField(default=apps.abstract.models.created_now_tz, editable=False, help_text='The object date creation.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=apps.abstract.models.created_now_tz, editable=False, help_text='The object last update.', verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text="Object checked as is_deleted can't be show.", verbose_name='Is deleted?')),
                ('title', models.CharField(help_text='The page title', max_length=80, verbose_name='Title')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('brief', models.TextField(blank=True, help_text='A brief with 150 characters limit.', max_length=150, null=True, verbose_name='A brief')),
                ('content', tinymce.models.HTMLField(blank=True, help_text='The body text in HTML format.', null=True, verbose_name='The page body')),
                ('comment', models.TextField(blank=True, help_text='A private area with comments for this post.', max_length=2000, null=True, verbose_name='Comments')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_by_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
